apiVersion: apps/v1
kind: Deployment
metadata:
  name: mern-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mern-app
  template:
    metadata:
      labels:
        app: mern-app
    spec:
      containers:
      - name: backend
        image: chibuzor1/dapp3:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5500
        env:   # Add this section for environment variables
        - name: HOSTPORT
          valueFrom:
            configMapKeyRef:
              name: mern-config   # Refers to your ConfigMap
              key: HOSTPORT 
        - name: MONGOOSE_URL
          valueFrom:
            secretKeyRef:
              name: mern-secrets
              key: MONGOOSE_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: mern-secrets
              key: JWT_SECRET
